---
pool: 
  name: "Azure Pipelines"
  vmImage: 'ubuntu-latest'

trigger:
  - main

jobs:
  - job: mavenjob
    displayName: maven
    steps:
      - task: Maven@3
        inputs:
          goals: 'package'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaVersionOption: '1.17'