---
pool: 
  name: "Azure Pipelines"
  vmImage: 'ubuntu-latest'

trigger:
  - main

jobs:
  - job: mavenjob
    displayName: maven
    steps:
      - task: Maven@3
        inputs:
          mavenPOMFile: 'D:\Java/pom.xml'
          goals: 'package'
          publishJUnitResults: true
          javaVersionOption: '1.17'
          javaHomeOption: 'Path'
          jdkDirectory: /usr/lib/jvm/java-17-openjdk-amd64
          mavenVersionOption: 'Path'
          mavenDirectory: /home/azureuser/apache-maven-3.9.0
          